name: TWRP 16 Builder

on:
  workflow_dispatch:
    inputs:
      TWRP_MANIFEST_URL:
        description: "TWRP manifest url"
        required: true
        default: "https://github.com/TWRP-Test/platform_manifest_twrp_aosp"
      TWRP_MANIFEST_BRANCH:
        description: "TWRP branch"
        required: true
        default: "twrp-16.0"
      DEVICE_TREE_URL:
        description: "Device tree urlL"
        required: true
        default: "https://github.com/kmiit/twrp_device_oplus_sm87xx"
      DEVICE_TREE_BRANCH:
        description: "Device tree branch"
        required: true
        default: "twrp-16.0"
      DEVICE_PATH:
        description: "Device path device/"
        required: true
        default: "oplus/sm87xx"
      DEVICE_NAME:
        description: "Device name"
        required: true
        default: "sm87xx"
      LUNCH_TARGET:
        description: "lunch twrp_ (default same as device name)"
        required: false
        default: ""
      BUILD_PARTITION:
        description: "Build partition"
        required: true
        default: "recovery"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Show build info
      id: show_build_info
      run: |
        {
          echo 'BUILD_INFO<<EOF'
          echo
          echo Manifest URL: ${{ github.event.inputs.TWRP_MANIFEST_URL }}
          echo Manifest Branch: ${{ github.event.inputs.TWRP_MANIFEST_BRANCH }}
          echo Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}
          echo Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
          echo Device Path: ${{ github.event.inputs.DEVICE_PATH }}
          echo Device name: ${{ github.event.inputs.DEVICE_NAME }}
          echo Lunch target: ${{ github.event.inputs.LUNCH_TARGET }}
          echo Build Target: ${{ github.event.inputs.BUILD_PARTITION }}.img
          echo Build date: `date`
          echo
          echo EOF
        } >> "$GITHUB_ENV"
        echo BUILD_DATE=`date +%F` >> "$GITHUB_ENV"

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
        
    - name: Setup zram
      run: |
        sudo apt install linux-modules-extra-$(uname -r) zram-tools -y
        sudo modprobe zram
        echo ----------------------------------------
        sudo sed -i 's/^#PERCENT=50/PERCENT=95/' /etc/default/zramswap
        sudo sed -i 's/^#PRIORITY=100/PRIORITY=1000/' /etc/default/zramswap
        sudo systemctl restart zramswap
        zramctl
        swapon --show
        
    - name: Check Out
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup environment
      run: |
        # sudo rm -rf /usr/local/.ghcup
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update && sudo apt upgrade -y
        sudo apt install repo -y
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor }}@users.noreply.github.com
        echo -e "$BUILD_INFO" >> INFO.txt
        echo "Change log:" >> INFO.txt
        set +e
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
        if [ $? -eq 0 ]; then
          git log "$LAST_TAG"..HEAD --pretty=format:"- %h-%an: %s" >> INFO.txt
        else
          git log --pretty=format:"- %h-%an: %s" >> INFO.txt
        fi
        cat INFO.txt

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true

    - name: Init source
      run: |
        repo init -u ${{ github.event.inputs.TWRP_MANIFEST_URL }} -b ${{ github.event.inputs.TWRP_MANIFEST_BRANCH }} --depth=1
        (while true; do echo "Syncing source..."; sleep 120; done) &
        KA_PID=$!
        repo sync
        export
        kill $KA_PID && exit 0

    - name: Setup device
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} device/${{ github.event.inputs.DEVICE_PATH }} --depth=1
        
    - name: Build TWRP
      run: |
        rm -rf .repo # remove source
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export USE_CCACHE=1
        export CCACHE_EXEC=$(command -v ccache)
        export CCACHE_DIR=.ccache
        export
        if [ -n "${{ github.event.inputs.LUNCH_TARGET }}" ]; then
          lunch twrp_${{ github.event.inputs.LUNCH_TARGET }}
        else
          lunch twrp_${{ github.event.inputs.DEVICE_NAME }}
        fi
        (while true; do echo `date +%T` "Building TWRP..."; free -h; sleep 10; done) &
        KA_PID=$!
        m ${{ github.event.inputs.BUILD_PARTITION }}image
        kill $KA_PID && exit 0

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          out/target/product/${{ github.event.inputs.DEVICE_PATH }}/${{ github.event.inputs.BUILD_TARGET }}.img
        name: TWRP-3.7.1-16-${{ github.event.inputs.DEVICE_NAME }}-${{ env.BUILD_DATE }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body_path: INFO.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}