name: TWRP 16 Builder

on:
  workflow_dispatch:
    inputs:
      TWRP_MANIFEST_URL:
        description: "TWRP manifest url"
        required: true
        default: "https://github.com/TWRP-Test/platform_manifest_twrp_aosp"
      TWRP_MANIFEST_BRANCH:
        description: "TWRP branch"
        required: true
        default: "twrp-16.0"
      DEVICE_TREE_URL:
        description: "Device tree urlL"
        required: true
        default: "https://github.com/kmiit/twrp_device_oplus_sm87xx"
      DEVICE_TREE_BRANCH:
        description: "Device tree branch"
        required: true
        default: "twrp-16.0"
      DEVICE_PATH:
        description: "Device path"
        required: true
        default: "device/oplus/sm87xx"
      DEVICE_NAME:
        description: "Device name"
        required: true
        default: "sm87xx"
      LUNCH_TARGET:
        description: "lunch twrp_ (default same as lunch target)"
        required: false
        default: ""
      BUILD_PARTITION:
        description: "Build partition"
        required: true
        default: "recovery"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Display build info
      run: |
        pwd
        cd ${GITHUB_WORKSPACE}
        pwd
        INFO_FILE=INFO.txt
        echo "::group::User Environment Variables"
        echo -e "Manifest URL: ${{ github.event.inputs.TWRP_MANIFEST_URL }}\n" \
                 "Manifest Branch: ${{ github.event.inputs.TWRP_MANIFEST_BRANCH }}\n" \
                 "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}\n" \
                 "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}\n" \
                 "Device Path: ${{ github.event.inputs.DEVICE_PATH }}\n" \
                 "Device name: ${{ github.event.inputs.DEVICE_NAME }}\n" \
                 "Lunch target: ${{ github.event.inputs.LUNCH_TARGET }}\n" \
                 "Build Target: ${{ github.event.inputs.BUILD_PARTITION }}.img\n" | tee $INFO_FILE
        echo "::endgroup::"

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 16384

    - name: Check Out
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        pwd
        cd ${GITHUB_WORKSPACE}
        pwd
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update && sudo apt upgrade -y
        sudo apt install repo -y
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        echo "Change log: \n" >> INFO.txt
        set +e
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
        if [ $? -eq 0 ]; then
          git log "$LAST_TAG"..HEAD --pretty=format:"- %h-%an: %s" | tee -a INFO.txt
        else
          git log --pretty=format:"- %h-%an: %s" | tee -a INFO.txt
        fi
        cat INFO.txt

    - name: Init source
      run: |
        pwd
        cd ${GITHUB_WORKSPACE}
        pwd
        repo init -u ${{ github.event.inputs.TWRP_MANIFEST_URL }} -b ${{ github.event.inputs.TWRP_MANIFEST_BRANCH }} --depth=1
        repo sync
    
    - name: Setup device
      run: |
        pwd
        cd ${GITHUB_WORKSPACE}
        pwd
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }} --depth=1
        
    - name: Build TWRP
      run: |
        pwd
        cd ${GITHUB_WORKSPACE}
        pwd
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        if [ -n "${{ github.event.inputs.LUNCH_TARGET }}" ]; then
          lunch twrp_${{ github.event.inputs.LUNCH_TARGET }}
        else
          lunch twrp_${{ github.event.inputs.DEVICE_NAME }}
        fi
        m ${{ github.event.inputs.BUILD_PARTITION }}image
        ls

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          ${GITHUB_WORKSPACE}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
          ${GITHUB_WORKSPACE}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
          ${GITHUB_WORKSPACE}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*vendor*.img
        name: TWRP-3.7.1-16-${{ github.event.inputs.DEVICE_NAME }}-${date +"%Y%m%d"}${{ github.run_id }}
        tag_name: TWRP-3.7.1-16-${{ github.event.inputs.DEVICE_NAME }}-${date +"%Y%m%d"}${{ github.run_id }}
        body_path: ${GITHUB_WORKSPACE}/INFO.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}